services:
  _defaults:
    autoconfigure: true
    autowire: true

  Ergebnis\Application\:
    exclude: "../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}"
    resource: "../src/*"

  Ergebnis\Application\Controller\:
    resource: "../src/Controller"
    tags:
      - "controller.service_arguments"
